# Generated by Django 2.2.5 on 2020-01-19 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=100)),
                ('contact', models.CharField(db_column='Contact', max_length=15, unique=True)),
                ('email', models.CharField(db_column='Email', max_length=60, unique=True)),
                ('subject', models.CharField(db_column='Subject', max_length=50)),
                ('mesg', models.TextField(db_column='Mesg')),
                ('time', models.DateTimeField(db_column='Time')),
            ],
            options={
                'db_table': 'enquiry',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('uid', models.AutoField(db_column='UID', primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='Username', max_length=30)),
                ('password', models.TextField(db_column='Password')),
                ('emailid', models.CharField(db_column='EmailID', max_length=60, unique=True)),
                ('contactno', models.CharField(db_column='ContactNo', max_length=20, unique=True)),
                ('creationtime', models.DateTimeField(db_column='CreationTime')),
                ('lastmodified', models.DateTimeField(blank=True, db_column='LastModified', null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
